version: "3"

tasks:
  apply-namespace:
    desc: "Apply Kubernetes Namespace"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubectl config set-context --current --namespace=demo-app

  deploy-traefik:
    desc: "Deploy Traefik using Helm"
    cmds:
      - helm repo add traefik https://traefik.github.io/charts
      - helm upgrade --install -n traefik --create-namespace traefik traefik/traefik --version 37.2.0

  apply-traefik-middleware:
    desc: "Deploy Traefik middleware"
    cmds:
      - "kubectl apply -f Middleware.yaml"

  deploy-postgres:
    desc: "Deploy PostgreSQL Database"
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - "helm upgrade --install postgresql \
          -n postgres bitnami/postgresql \
          --set auth.postgresPassword=foobarbaz \
          --version 18.1.1 \
          --create-namespace"

  get-postgres-password:
    desc: "Get PostgreSQL password"
    cmds:
      - "kubectl get secret --namespace demo-app postgresql -o jsonpath=\"{.data.postgres-password}\" | base64 --decode"

  apply-all:
    desc: "Apply all Kubernetes resources"
    cmds:
      - task: apply-namespace
      - task: deploy-traefik
      - task: apply-traefik-middleware
      - task: deploy-postgres