version: "3"

tasks:
  apply-namespace:
    desc: "Apply Kubernetes Namespace"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubectl config set-context --current --namespace=demo-app

  deploy-traefik:
    desc: "Deploy Traefik using Helm"
    cmds:
      - helm repo add traefik https://traefik.github.io/charts
      - helm upgrade --install -n traefik --create-namespace traefik traefik/traefik --version 37.2.0

  apply-traefik-middleware:
    desc: "Deploy Traefik middleware"
    cmds:
      - "kubectl apply -f Middleware.yaml"

  deploy-postgres:
    desc: "Deploy PostgreSQL Database"
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - "helm upgrade --install postgresql \
          -n postgres bitnami/postgresql \
          --set auth.postgresPassword=foobarbaz \
          --version 18.1.1 \
          --create-namespace"
          
  deploy-prometheus-stack:
    desc: "Deploy Prometheus Stack using Helm"
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo add grafana https://grafana.github.io/helm-charts
      - "helm upgrade --install prometheus-stack \
          -n monitoring prometheus-community/kube-prometheus-stack \
          --version 79.1.1 \
          --create-namespace"

  get-grafana-admin-password:
    desc: "Get Grafana admin password"
    cmds:
      - |
        kubectl get secret -n monitoring prometheus-stack-grafana \
          -o jsonpath="{.data.admin-password}" | base64 --decode ; echo

  deploy-loki:
    desc: "Deploy Loki for logging"
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts
      - |
        helm upgrade --install loki grafana/loki \
          -n monitoring \
          --version 5.35.0 \
          --set promtail.enabled=true \
          --set loki.persistence.enabled=false \

  deploy-tempo:
    desc: "Deploy Tempo for tracing"
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts
      - "helm upgrade --install tempo grafana/tempo \
          -n monitoring \
          --version 1.24.0 \
          --create-namespace \
          --set tempo.metrics.enabled=true \
          --set storage.trace.backend=mem"

  deploy-opentelemetry-collector:
    desc: "Deploy OpenTelemetry Collector"
    cmds:
      - helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
      - |
        helm upgrade --install otel-collector open-telemetry/opentelemetry-collector \
          -n monitoring \
          --version 0.138.1 \
          --create-namespace \
          --set mode=deployment \
          --set config.receivers.otlp.protocols.http.enabled=true \
          --set config.receivers.otlp.protocols.grpc.enabled=true \
          --set config.exporters.otlp.endpoint="http://tempo.monitoring.svc.cluster.local:4317" \
          --set config.service.pipelines.traces.receivers[0]=otlp \
          --set config.service.pipelines.traces.exporters[0]=otlp

  apply-all:
    desc: "Apply all Kubernetes resources"
    cmds:
      - task: apply-namespace
      - task: deploy-traefik
      - task: apply-traefik-middleware
      - task: deploy-postgres
      - task: deploy-prometheus-stack
      - task: deploy-loki
      - task: deploy-tempo